kind: Deployment
apiVersion: apps/v1
metadata:
  name: webelight_practical_test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webelight_practical_test
  template:
    metadata:
      labels:
        app: webelight_practical_test
    spec:
      imagePullSecrets:
        - name: dockerregistry
      containers:
      - name: paradise-backed
        image: labs47b/paradise:{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PORT
          - name: MONGO_DB_NAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_DB_NAME
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: secret
                key: REDIS_PORT
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: secret
                 key: REDIS_HOST
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secret
                key: PORT
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

